### ISSUE TITLE
Resonate Server, Hosting, K8s

### ISSUE THREAD

**Issue by dtornow** [resonatehq/docs#24]
Add a minimal K8s manifest to host the Resonate Server/SQLite on K8s

Starting point

```
---
apiVersion: v1
kind: Service
metadata:
  name: resonate
  namespace: default
spec:
  selector:
    app: resonate
  ports:
    - port: 8001
      name: api
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resonate
  namespace: default
spec:
  serviceName: resonate
  replicas: 1
  selector:
    matchLabels:
      app: resonate
  template:
    metadata:
      labels:
        app: resonate
    spec:
      containers:
        - name: resonate
          image: # TODO: image
          ports:
            - containerPort: 8001
              name: api
```
